"use strict";
/* Autogenerated file. Do not edit manually. */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CollectFees = exports.SwapExactOut = exports.SwapExactIn = exports.RemoveLiquidity = exports.AddLiquidity = exports.CreatePoolWithLiquidity = void 0;
/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */
/*
  Fuels version: 0.101.1
  Forc version: 0.68.1
  Fuel-Core version: 0.43.1
*/
var CreatePoolWithLiquidity_1 = require("./CreatePoolWithLiquidity");
Object.defineProperty(exports, "CreatePoolWithLiquidity", { enumerable: true, get: function () { return CreatePoolWithLiquidity_1.CreatePoolWithLiquidity; } });
var AddLiquidity_1 = require("./AddLiquidity");
Object.defineProperty(exports, "AddLiquidity", { enumerable: true, get: function () { return AddLiquidity_1.AddLiquidity; } });
var RemoveLiquidity_1 = require("./RemoveLiquidity");
Object.defineProperty(exports, "RemoveLiquidity", { enumerable: true, get: function () { return RemoveLiquidity_1.RemoveLiquidity; } });
var SwapExactIn_1 = require("./SwapExactIn");
Object.defineProperty(exports, "SwapExactIn", { enumerable: true, get: function () { return SwapExactIn_1.SwapExactIn; } });
var SwapExactOut_1 = require("./SwapExactOut");
Object.defineProperty(exports, "SwapExactOut", { enumerable: true, get: function () { return SwapExactOut_1.SwapExactOut; } });
var CollectFees_1 = require("./CollectFees");
Object.defineProperty(exports, "CollectFees", { enumerable: true, get: function () { return CollectFees_1.CollectFees; } });
//# sourceMappingURL=index.js.map