"use strict";
/* Autogenerated file. Do not edit manually. */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReactorPoolContract = exports.ReactorPoolContractInterface = exports.ReentrancyErrorOutput = exports.ReentrancyErrorInput = exports.PauseErrorOutput = exports.PauseErrorInput = exports.InitializationErrorOutput = exports.InitializationErrorInput = exports.ErrorOutput = exports.ErrorInput = exports.AccessErrorOutput = exports.AccessErrorInput = void 0;
/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */
/*
  Fuels version: 0.101.1
  Forc version: 0.68.1
  Fuel-Core version: 0.43.1
*/
const fuels_1 = require("fuels");
var AccessErrorInput;
(function (AccessErrorInput) {
    AccessErrorInput["NotOwner"] = "NotOwner";
})(AccessErrorInput || (exports.AccessErrorInput = AccessErrorInput = {}));
;
var AccessErrorOutput;
(function (AccessErrorOutput) {
    AccessErrorOutput["NotOwner"] = "NotOwner";
})(AccessErrorOutput || (exports.AccessErrorOutput = AccessErrorOutput = {}));
;
var ErrorInput;
(function (ErrorInput) {
    ErrorInput["ZeroDivisor"] = "ZeroDivisor";
})(ErrorInput || (exports.ErrorInput = ErrorInput = {}));
;
var ErrorOutput;
(function (ErrorOutput) {
    ErrorOutput["ZeroDivisor"] = "ZeroDivisor";
})(ErrorOutput || (exports.ErrorOutput = ErrorOutput = {}));
;
var InitializationErrorInput;
(function (InitializationErrorInput) {
    InitializationErrorInput["CannotReinitialized"] = "CannotReinitialized";
})(InitializationErrorInput || (exports.InitializationErrorInput = InitializationErrorInput = {}));
;
var InitializationErrorOutput;
(function (InitializationErrorOutput) {
    InitializationErrorOutput["CannotReinitialized"] = "CannotReinitialized";
})(InitializationErrorOutput || (exports.InitializationErrorOutput = InitializationErrorOutput = {}));
;
var PauseErrorInput;
(function (PauseErrorInput) {
    PauseErrorInput["Paused"] = "Paused";
    PauseErrorInput["NotPaused"] = "NotPaused";
})(PauseErrorInput || (exports.PauseErrorInput = PauseErrorInput = {}));
;
var PauseErrorOutput;
(function (PauseErrorOutput) {
    PauseErrorOutput["Paused"] = "Paused";
    PauseErrorOutput["NotPaused"] = "NotPaused";
})(PauseErrorOutput || (exports.PauseErrorOutput = PauseErrorOutput = {}));
;
var ReentrancyErrorInput;
(function (ReentrancyErrorInput) {
    ReentrancyErrorInput["NonReentrant"] = "NonReentrant";
})(ReentrancyErrorInput || (exports.ReentrancyErrorInput = ReentrancyErrorInput = {}));
;
var ReentrancyErrorOutput;
(function (ReentrancyErrorOutput) {
    ReentrancyErrorOutput["NonReentrant"] = "NonReentrant";
})(ReentrancyErrorOutput || (exports.ReentrancyErrorOutput = ReentrancyErrorOutput = {}));
;
const abi = {
    "programType": "contract",
    "specVersion": "1",
    "encodingVersion": "1",
    "concreteTypes": [
        {
            "type": "()",
            "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
            "type": "(struct std::asset_id::AssetId, struct std::asset_id::AssetId, u64)",
            "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60",
            "metadataTypeId": 2
        },
        {
            "type": "(struct std::asset_id::AssetId, u64, u64)",
            "concreteTypeId": "a7a9c903b01d420859932823a44a01d007ff9fc03cbde5c89021a0cd00a3b8f2",
            "metadataTypeId": 3
        },
        {
            "type": "(struct sway_libs::signed_integers::i256::I256, struct sway_libs::signed_integers::i256::I256)",
            "concreteTypeId": "3fa8627a84b71ee8f24fd08a49e0c24b26ebd8812d83105363ea2522a6bd1ebf",
            "metadataTypeId": 1
        },
        {
            "type": "(u64, u64)",
            "concreteTypeId": "41bd1a98f0a59642d8f824c805b798a5f268d1f7d05808eb05c4189c493f1be0",
            "metadataTypeId": 0
        },
        {
            "type": "bool",
            "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        },
        {
            "type": "enum cl_math::math_errors::MathError",
            "concreteTypeId": "e2cf0802296424074f790dd21c4edfa1afd413199abcb82ac40ddd7d353a16ba",
            "metadataTypeId": 5
        },
        {
            "type": "enum interfaces::errors::InputError",
            "concreteTypeId": "2c16264fa4a4e0c4dceefe1b6eee32bbd8f32e19b79110d831a389a95f37c915",
            "metadataTypeId": 6
        },
        {
            "type": "enum standards::src5::AccessError",
            "concreteTypeId": "3f702ea3351c9c1ece2b84048006c8034a24cbc2bad2e740d0412b4172951d3d",
            "metadataTypeId": 7
        },
        {
            "type": "enum standards::src5::State",
            "concreteTypeId": "192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c",
            "metadataTypeId": 8
        },
        {
            "type": "enum std::identity::Identity",
            "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
            "metadataTypeId": 9
        },
        {
            "type": "enum std::option::Option<struct interfaces::data_structures::PoolInfo>",
            "concreteTypeId": "d401ba55f88fe188ba6bd654f67d3adf65a36094299765bb04cdeef83e88cf55",
            "metadataTypeId": 10,
            "typeArguments": [
                "6905cfe3fc2391bd71594eaa385c23894736a83b7058148aa03e222de7e9dcba"
            ]
        },
        {
            "type": "enum std::option::Option<struct interfaces::data_structures::PoolState>",
            "concreteTypeId": "9e719caa3cf7f08dfc3e5f211ce3d1a468fa5d31cdc904233d423bc4c9364492",
            "metadataTypeId": 10,
            "typeArguments": [
                "32989478a7ca8a471e1e48cd576a649f356560175f086be3abd4ead8aa432f69"
            ]
        },
        {
            "type": "enum std::option::Option<struct interfaces::data_structures::PositionInfo>",
            "concreteTypeId": "221d25780d1141f3844af6322761cb2f21368d1026d4a32ff39b06d282bceebf",
            "metadataTypeId": 10,
            "typeArguments": [
                "a03dbe5c2b4f25fb5fb9b4f753fb7e920c73590885dcf51e29c289c9f87c8118"
            ]
        },
        {
            "type": "enum std::option::Option<struct std::string::String>",
            "concreteTypeId": "7c06d929390a9aeeb8ffccf8173ac0d101a9976d99dda01cce74541a81e75ac0",
            "metadataTypeId": 10,
            "typeArguments": [
                "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
            ]
        },
        {
            "type": "enum std::option::Option<u64>",
            "concreteTypeId": "d852149004cc9ec0bbe7dc4e37bffea1d41469b759512b6136f2e865a4c06e7d",
            "metadataTypeId": 10,
            "typeArguments": [
                "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
            ]
        },
        {
            "type": "enum std::option::Option<u8>",
            "concreteTypeId": "2da102c46c7263beeed95818cd7bee801716ba8303dddafdcd0f6c9efda4a0f1",
            "metadataTypeId": 10,
            "typeArguments": [
                "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
            ]
        },
        {
            "type": "enum sway_libs::ownership::errors::InitializationError",
            "concreteTypeId": "1dfe7feadc1d9667a4351761230f948744068a090fe91b1bc6763a90ed5d3893",
            "metadataTypeId": 11
        },
        {
            "type": "enum sway_libs::pausable::errors::PauseError",
            "concreteTypeId": "8b3afcadf894415a10b09fc3717487e33802c8ffbb030edafe84ca4a71b280bc",
            "metadataTypeId": 12
        },
        {
            "type": "enum sway_libs::reentrancy::errors::ReentrancyError",
            "concreteTypeId": "4d216c57b3357523323f59401c7355785b41bdf832f6e1106272186b94797038",
            "metadataTypeId": 13
        },
        {
            "type": "enum sway_libs::signed_integers::errors::Error",
            "concreteTypeId": "c14ce387a2e1be6031c07283e466ad30db558277d3ff7f694daa635825d612a4",
            "metadataTypeId": 14
        },
        {
            "type": "str",
            "concreteTypeId": "8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a"
        },
        {
            "type": "struct interfaces::data_structures::PoolInfo",
            "concreteTypeId": "6905cfe3fc2391bd71594eaa385c23894736a83b7058148aa03e222de7e9dcba",
            "metadataTypeId": 17
        },
        {
            "type": "struct interfaces::data_structures::PoolState",
            "concreteTypeId": "32989478a7ca8a471e1e48cd576a649f356560175f086be3abd4ead8aa432f69",
            "metadataTypeId": 18
        },
        {
            "type": "struct interfaces::data_structures::PositionInfo",
            "concreteTypeId": "a03dbe5c2b4f25fb5fb9b4f753fb7e920c73590885dcf51e29c289c9f87c8118",
            "metadataTypeId": 19
        },
        {
            "type": "struct interfaces::data_structures::TickInfo",
            "concreteTypeId": "566fefd02783b1bed85bcd428a63d598af31a37122ce0cf0045531fdc4aeae14",
            "metadataTypeId": 21
        },
        {
            "type": "struct interfaces::events::BurnEvent",
            "concreteTypeId": "362a6a689aa3d6b3e2d50426f7c94ce2717b22f1df0b7ffe541cbcb25e0b9c65",
            "metadataTypeId": 22
        },
        {
            "type": "struct interfaces::events::CollectEvent",
            "concreteTypeId": "80a6b331abab8b7ae99401e5abbe1b32a5e31ba95bb98ccc2da6c988a669b828",
            "metadataTypeId": 23
        },
        {
            "type": "struct interfaces::events::CollectProtocolEvent",
            "concreteTypeId": "1643eb307a66426c1cbebe217ae1af8914a092146d96072387f4811c1119c213",
            "metadataTypeId": 24
        },
        {
            "type": "struct interfaces::events::CreatePoolEvent",
            "concreteTypeId": "a9a76f9e31034cee0ebff18e0c0dc3b3511e277ab8644fb5b42ab97d62b52037",
            "metadataTypeId": 25
        },
        {
            "type": "struct interfaces::events::EnableFeeAmountEvent",
            "concreteTypeId": "0c9c42a4c01c2b27054127b9c4bb9c21c1e449c182cfa19fa56104c4509ac81e",
            "metadataTypeId": 26
        },
        {
            "type": "struct interfaces::events::MintEvent",
            "concreteTypeId": "ae2069277682335a733c89d400032730e629e08e19f5127cba9ddd54854c1ff6",
            "metadataTypeId": 27
        },
        {
            "type": "struct interfaces::events::SetFeeProtocolEvent",
            "concreteTypeId": "462c8cb4b6f2e25c6687a0e70a48256db33da6c8f214f3a8e2211fd85bb5e773",
            "metadataTypeId": 28
        },
        {
            "type": "struct interfaces::events::SwapEvent",
            "concreteTypeId": "6e2b2beb181a5f3d2c643986a5df4197407de6383085035d82fe20a2d2d779bf",
            "metadataTypeId": 29
        },
        {
            "type": "struct standards::src20::SetDecimalsEvent",
            "concreteTypeId": "fbe071a6e7ca2b2b5e503e82638f9f11c861a6fb452b65473eca8260db87392d",
            "metadataTypeId": 30
        },
        {
            "type": "struct standards::src20::SetNameEvent",
            "concreteTypeId": "6ce295b0fb4c1c15e8ed1cfa4babda47d8a04940a5266a3229e12243a2e37c2c",
            "metadataTypeId": 31
        },
        {
            "type": "struct standards::src20::SetSymbolEvent",
            "concreteTypeId": "a8a4b78066c51a50da6349bd395fe1c67e774d75c1db2c5c22288a432d7a363d",
            "metadataTypeId": 32
        },
        {
            "type": "struct std::asset_id::AssetId",
            "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
            "metadataTypeId": 34
        },
        {
            "type": "struct std::string::String",
            "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
            "metadataTypeId": 38
        },
        {
            "type": "struct sway_libs::ownership::events::OwnershipSet",
            "concreteTypeId": "e1ef35033ea9d2956f17c3292dea4a46ce7d61fdf37bbebe03b7b965073f43b5",
            "metadataTypeId": 39
        },
        {
            "type": "struct sway_libs::ownership::events::OwnershipTransferred",
            "concreteTypeId": "b3fffbcb3158d7c010c31b194b60fb7857adb4ad61bdcf4b8b42958951d9f308",
            "metadataTypeId": 40
        },
        {
            "type": "struct sway_libs::signed_integers::i256::I256",
            "concreteTypeId": "1c791a2f63a6d482f33e38564a4c4f67f2351f36419d0c750ce825e233c86ae1",
            "metadataTypeId": 41
        },
        {
            "type": "struct sway_libs::signed_integers::i64::I64",
            "concreteTypeId": "5505fc50822ba746456a5300ef2739df1284948387efd9f4c4f9bf06827368f2",
            "metadataTypeId": 42
        },
        {
            "type": "u256",
            "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
            "type": "u64",
            "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
            "type": "u8",
            "concreteTypeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
        }
    ],
    "metadataTypes": [
        {
            "type": "(_, _)",
            "metadataTypeId": 0,
            "components": [
                {
                    "name": "__tuple_element",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "__tuple_element",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "(_, _)",
            "metadataTypeId": 1,
            "components": [
                {
                    "name": "__tuple_element",
                    "typeId": 41
                },
                {
                    "name": "__tuple_element",
                    "typeId": 41
                }
            ]
        },
        {
            "type": "(_, _, _)",
            "metadataTypeId": 2,
            "components": [
                {
                    "name": "__tuple_element",
                    "typeId": 34
                },
                {
                    "name": "__tuple_element",
                    "typeId": 34
                },
                {
                    "name": "__tuple_element",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "(_, _, _)",
            "metadataTypeId": 3,
            "components": [
                {
                    "name": "__tuple_element",
                    "typeId": 34
                },
                {
                    "name": "__tuple_element",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "__tuple_element",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "b256",
            "metadataTypeId": 4
        },
        {
            "type": "enum cl_math::math_errors::MathError",
            "metadataTypeId": 5,
            "components": [
                {
                    "name": "ZeroValue",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                },
                {
                    "name": "TickSpacingError",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                },
                {
                    "name": "ResultIsU64Max",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                },
                {
                    "name": "TickRange",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                },
                {
                    "name": "InvalidTick",
                    "typeId": 42
                },
                {
                    "name": "InvalidSqrtRatio",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "DivisionByZero",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                }
            ]
        },
        {
            "type": "enum interfaces::errors::InputError",
            "metadataTypeId": 6,
            "components": [
                {
                    "name": "PoolAlreadyExists",
                    "typeId": 2
                },
                {
                    "name": "PoolDoesNotExist",
                    "typeId": 2
                },
                {
                    "name": "InvalidAsset",
                    "typeId": 34
                },
                {
                    "name": "IdenticalAssets",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                },
                {
                    "name": "UnsortedAssetPair",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                },
                {
                    "name": "PoolInvariantViolation",
                    "typeId": 0
                },
                {
                    "name": "AssetSymbolNotSet",
                    "typeId": 34
                },
                {
                    "name": "AssetDecimalsNotSet",
                    "typeId": 34
                }
            ]
        },
        {
            "type": "enum standards::src5::AccessError",
            "metadataTypeId": 7,
            "components": [
                {
                    "name": "NotOwner",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                }
            ]
        },
        {
            "type": "enum standards::src5::State",
            "metadataTypeId": 8,
            "components": [
                {
                    "name": "Uninitialized",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                },
                {
                    "name": "Initialized",
                    "typeId": 9
                },
                {
                    "name": "Revoked",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                }
            ]
        },
        {
            "type": "enum std::identity::Identity",
            "metadataTypeId": 9,
            "components": [
                {
                    "name": "Address",
                    "typeId": 33
                },
                {
                    "name": "ContractId",
                    "typeId": 37
                }
            ]
        },
        {
            "type": "enum std::option::Option",
            "metadataTypeId": 10,
            "components": [
                {
                    "name": "None",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                },
                {
                    "name": "Some",
                    "typeId": 15
                }
            ],
            "typeParameters": [
                15
            ]
        },
        {
            "type": "enum sway_libs::ownership::errors::InitializationError",
            "metadataTypeId": 11,
            "components": [
                {
                    "name": "CannotReinitialized",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                }
            ]
        },
        {
            "type": "enum sway_libs::pausable::errors::PauseError",
            "metadataTypeId": 12,
            "components": [
                {
                    "name": "Paused",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                },
                {
                    "name": "NotPaused",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                }
            ]
        },
        {
            "type": "enum sway_libs::reentrancy::errors::ReentrancyError",
            "metadataTypeId": 13,
            "components": [
                {
                    "name": "NonReentrant",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                }
            ]
        },
        {
            "type": "enum sway_libs::signed_integers::errors::Error",
            "metadataTypeId": 14,
            "components": [
                {
                    "name": "ZeroDivisor",
                    "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
                }
            ]
        },
        {
            "type": "generic T",
            "metadataTypeId": 15
        },
        {
            "type": "raw untyped ptr",
            "metadataTypeId": 16
        },
        {
            "type": "struct interfaces::data_structures::PoolInfo",
            "metadataTypeId": 17,
            "components": [
                {
                    "name": "id",
                    "typeId": 2
                },
                {
                    "name": "tick_spacing",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "max_liq_per_tick",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                }
            ]
        },
        {
            "type": "struct interfaces::data_structures::PoolState",
            "metadataTypeId": 18,
            "components": [
                {
                    "name": "sqrtPriceX96",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "tick",
                    "typeId": 42
                },
                {
                    "name": "fee_protocol",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "unlocked",
                    "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
                },
                {
                    "name": "feeGrowthGlobal0X128",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "feeGrowthGlobal1X128",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "protocolFees",
                    "typeId": 20
                },
                {
                    "name": "liquidity",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "reserve_0",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "reserve_1",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "struct interfaces::data_structures::PositionInfo",
            "metadataTypeId": 19,
            "components": [
                {
                    "name": "liquidity",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "feeGrowthInside0LastX128",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "feeGrowthInside1LastX128",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "tokensOwed0",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "tokensOwed1",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "struct interfaces::data_structures::ProtocolFees",
            "metadataTypeId": 20,
            "components": [
                {
                    "name": "token0",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "token1",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "struct interfaces::data_structures::TickInfo",
            "metadataTypeId": 21,
            "components": [
                {
                    "name": "liquidity_gross",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "liquidity_net",
                    "typeId": 41
                },
                {
                    "name": "fee_growth_outside_0_X128",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "fee_growth_outside_1_X128",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "initialized",
                    "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
                }
            ]
        },
        {
            "type": "struct interfaces::events::BurnEvent",
            "metadataTypeId": 22,
            "components": [
                {
                    "name": "pool_id",
                    "typeId": 2
                },
                {
                    "name": "recipient",
                    "typeId": 9
                },
                {
                    "name": "liquidity",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "tick_lower",
                    "typeId": 42
                },
                {
                    "name": "tick_upper",
                    "typeId": 42
                },
                {
                    "name": "amount_0_actual",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "amount_1_actual",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "struct interfaces::events::CollectEvent",
            "metadataTypeId": 23,
            "components": [
                {
                    "name": "pool_id",
                    "typeId": 2
                },
                {
                    "name": "position_owner",
                    "typeId": 9
                },
                {
                    "name": "recipient",
                    "typeId": 9
                },
                {
                    "name": "tick_lower",
                    "typeId": 42
                },
                {
                    "name": "tick_upper",
                    "typeId": 42
                },
                {
                    "name": "amount_0",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "amount_1",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "struct interfaces::events::CollectProtocolEvent",
            "metadataTypeId": 24,
            "components": [
                {
                    "name": "pool_id",
                    "typeId": 2
                },
                {
                    "name": "owner",
                    "typeId": 9
                },
                {
                    "name": "recipient",
                    "typeId": 9
                },
                {
                    "name": "amount_0",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "amount_1",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "struct interfaces::events::CreatePoolEvent",
            "metadataTypeId": 25,
            "components": [
                {
                    "name": "pool_id",
                    "typeId": 2
                },
                {
                    "name": "sqrt_price_x96",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                }
            ]
        },
        {
            "type": "struct interfaces::events::EnableFeeAmountEvent",
            "metadataTypeId": 26,
            "components": [
                {
                    "name": "fee",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "tick_spacing",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "struct interfaces::events::MintEvent",
            "metadataTypeId": 27,
            "components": [
                {
                    "name": "nft_id",
                    "typeId": 34
                },
                {
                    "name": "pool_id",
                    "typeId": 2
                },
                {
                    "name": "recipient",
                    "typeId": 9
                },
                {
                    "name": "liquidity",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "tick_lower",
                    "typeId": 42
                },
                {
                    "name": "tick_upper",
                    "typeId": 42
                },
                {
                    "name": "amount_0_actual",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "amount_1_actual",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "struct interfaces::events::SetFeeProtocolEvent",
            "metadataTypeId": 28,
            "components": [
                {
                    "name": "fee_protocol_0_old",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "fee_protocol_1_old",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "fee_protocol_0_new",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "fee_protocol_1_new",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "struct interfaces::events::SwapEvent",
            "metadataTypeId": 29,
            "components": [
                {
                    "name": "pool_id",
                    "typeId": 2
                },
                {
                    "name": "recipient",
                    "typeId": 9
                },
                {
                    "name": "asset_0_in",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "asset_1_in",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "asset_0_out",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "asset_1_out",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "sqrt_price_x96",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "liquidity",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                },
                {
                    "name": "tick",
                    "typeId": 42
                }
            ]
        },
        {
            "type": "struct standards::src20::SetDecimalsEvent",
            "metadataTypeId": 30,
            "components": [
                {
                    "name": "asset",
                    "typeId": 34
                },
                {
                    "name": "decimals",
                    "typeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
                },
                {
                    "name": "sender",
                    "typeId": 9
                }
            ]
        },
        {
            "type": "struct standards::src20::SetNameEvent",
            "metadataTypeId": 31,
            "components": [
                {
                    "name": "asset",
                    "typeId": 34
                },
                {
                    "name": "name",
                    "typeId": 10,
                    "typeArguments": [
                        {
                            "name": "",
                            "typeId": 38
                        }
                    ]
                },
                {
                    "name": "sender",
                    "typeId": 9
                }
            ]
        },
        {
            "type": "struct standards::src20::SetSymbolEvent",
            "metadataTypeId": 32,
            "components": [
                {
                    "name": "asset",
                    "typeId": 34
                },
                {
                    "name": "symbol",
                    "typeId": 10,
                    "typeArguments": [
                        {
                            "name": "",
                            "typeId": 38
                        }
                    ]
                },
                {
                    "name": "sender",
                    "typeId": 9
                }
            ]
        },
        {
            "type": "struct std::address::Address",
            "metadataTypeId": 33,
            "components": [
                {
                    "name": "bits",
                    "typeId": 4
                }
            ]
        },
        {
            "type": "struct std::asset_id::AssetId",
            "metadataTypeId": 34,
            "components": [
                {
                    "name": "bits",
                    "typeId": 4
                }
            ]
        },
        {
            "type": "struct std::bytes::Bytes",
            "metadataTypeId": 35,
            "components": [
                {
                    "name": "buf",
                    "typeId": 36
                },
                {
                    "name": "len",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "struct std::bytes::RawBytes",
            "metadataTypeId": 36,
            "components": [
                {
                    "name": "ptr",
                    "typeId": 16
                },
                {
                    "name": "cap",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        },
        {
            "type": "struct std::contract_id::ContractId",
            "metadataTypeId": 37,
            "components": [
                {
                    "name": "bits",
                    "typeId": 4
                }
            ]
        },
        {
            "type": "struct std::string::String",
            "metadataTypeId": 38,
            "components": [
                {
                    "name": "bytes",
                    "typeId": 35
                }
            ]
        },
        {
            "type": "struct sway_libs::ownership::events::OwnershipSet",
            "metadataTypeId": 39,
            "components": [
                {
                    "name": "new_owner",
                    "typeId": 9
                }
            ]
        },
        {
            "type": "struct sway_libs::ownership::events::OwnershipTransferred",
            "metadataTypeId": 40,
            "components": [
                {
                    "name": "new_owner",
                    "typeId": 9
                },
                {
                    "name": "previous_owner",
                    "typeId": 9
                }
            ]
        },
        {
            "type": "struct sway_libs::signed_integers::i256::I256",
            "metadataTypeId": 41,
            "components": [
                {
                    "name": "underlying",
                    "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                }
            ]
        },
        {
            "type": "struct sway_libs::signed_integers::i64::I64",
            "metadataTypeId": 42,
            "components": [
                {
                    "name": "underlying",
                    "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ]
        }
    ],
    "functions": [
        {
            "inputs": [],
            "name": "owner",
            "output": "192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [],
            "name": "is_paused",
            "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [],
            "name": "pause",
            "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "write"
                    ]
                }
            ]
        },
        {
            "inputs": [],
            "name": "unpause",
            "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "write"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "asset",
                    "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
                }
            ],
            "name": "decimals",
            "output": "2da102c46c7263beeed95818cd7bee801716ba8303dddafdcd0f6c9efda4a0f1",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "asset_id",
                    "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
                }
            ],
            "name": "name",
            "output": "7c06d929390a9aeeb8ffccf8173ac0d101a9976d99dda01cce74541a81e75ac0",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "asset_id",
                    "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
                }
            ],
            "name": "symbol",
            "output": "7c06d929390a9aeeb8ffccf8173ac0d101a9976d99dda01cce74541a81e75ac0",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [],
            "name": "total_assets",
            "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "asset",
                    "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
                }
            ],
            "name": "total_supply",
            "output": "d852149004cc9ec0bbe7dc4e37bffea1d41469b759512b6136f2e865a4c06e7d",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "pool_id",
                    "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60"
                },
                {
                    "name": "tick_lower",
                    "concreteTypeId": "5505fc50822ba746456a5300ef2739df1284948387efd9f4c4f9bf06827368f2"
                },
                {
                    "name": "tick_upper",
                    "concreteTypeId": "5505fc50822ba746456a5300ef2739df1284948387efd9f4c4f9bf06827368f2"
                },
                {
                    "name": "liquidity",
                    "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                }
            ],
            "name": "burn",
            "output": "41bd1a98f0a59642d8f824c805b798a5f268d1f7d05808eb05c4189c493f1be0",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read",
                        "write"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "pool_id",
                    "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60"
                },
                {
                    "name": "recipient",
                    "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
                },
                {
                    "name": "tick_lower",
                    "concreteTypeId": "5505fc50822ba746456a5300ef2739df1284948387efd9f4c4f9bf06827368f2"
                },
                {
                    "name": "tick_upper",
                    "concreteTypeId": "5505fc50822ba746456a5300ef2739df1284948387efd9f4c4f9bf06827368f2"
                },
                {
                    "name": "amount_0_requested",
                    "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "amount_1_requested",
                    "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ],
            "name": "collect",
            "output": "41bd1a98f0a59642d8f824c805b798a5f268d1f7d05808eb05c4189c493f1be0",
            "attributes": [
                {
                    "name": "payable",
                    "arguments": []
                },
                {
                    "name": "storage",
                    "arguments": [
                        "read",
                        "write"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "pool_id",
                    "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60"
                },
                {
                    "name": "recipient",
                    "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
                },
                {
                    "name": "amount_0_requested",
                    "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "amount_1_requested",
                    "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ],
            "name": "collect_protocol",
            "output": "41bd1a98f0a59642d8f824c805b798a5f268d1f7d05808eb05c4189c493f1be0",
            "attributes": [
                {
                    "name": "payable",
                    "arguments": []
                },
                {
                    "name": "storage",
                    "arguments": [
                        "read",
                        "write"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "token_0_id",
                    "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
                },
                {
                    "name": "token_1_id",
                    "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
                },
                {
                    "name": "fee",
                    "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "sqrt_price_x96",
                    "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                }
            ],
            "name": "create_pool",
            "output": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read",
                        "write"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "fee",
                    "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "tick_spacing",
                    "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ],
            "name": "enable_fee_amount",
            "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read",
                        "write"
                    ]
                }
            ]
        },
        {
            "inputs": [],
            "name": "initialize_fee_amount_tick_spacing",
            "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read",
                        "write"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "fee_amount",
                    "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ],
            "name": "is_fee_amount_enabled",
            "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "pool_id",
                    "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60"
                },
                {
                    "name": "tick",
                    "concreteTypeId": "5505fc50822ba746456a5300ef2739df1284948387efd9f4c4f9bf06827368f2"
                }
            ],
            "name": "is_tick_initialized",
            "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "pool_id",
                    "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60"
                },
                {
                    "name": "to",
                    "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
                },
                {
                    "name": "tick_lower",
                    "concreteTypeId": "5505fc50822ba746456a5300ef2739df1284948387efd9f4c4f9bf06827368f2"
                },
                {
                    "name": "tick_upper",
                    "concreteTypeId": "5505fc50822ba746456a5300ef2739df1284948387efd9f4c4f9bf06827368f2"
                },
                {
                    "name": "liquidity",
                    "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                }
            ],
            "name": "mint",
            "output": "a7a9c903b01d420859932823a44a01d007ff9fc03cbde5c89021a0cd00a3b8f2",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read",
                        "write"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "pool_id",
                    "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60"
                }
            ],
            "name": "pool_info",
            "output": "d401ba55f88fe188ba6bd654f67d3adf65a36094299765bb04cdeef83e88cf55",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "pool_id",
                    "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60"
                }
            ],
            "name": "pool_state",
            "output": "9e719caa3cf7f08dfc3e5f211ce3d1a468fa5d31cdc904233d423bc4c9364492",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "pool_id",
                    "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60"
                },
                {
                    "name": "owner",
                    "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
                },
                {
                    "name": "tick_lower",
                    "concreteTypeId": "5505fc50822ba746456a5300ef2739df1284948387efd9f4c4f9bf06827368f2"
                },
                {
                    "name": "tick_upper",
                    "concreteTypeId": "5505fc50822ba746456a5300ef2739df1284948387efd9f4c4f9bf06827368f2"
                }
            ],
            "name": "position_info",
            "output": "221d25780d1141f3844af6322761cb2f21368d1026d4a32ff39b06d282bceebf",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "pool_id",
                    "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60"
                },
                {
                    "name": "fee_protocol_0",
                    "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                },
                {
                    "name": "fee_protocol_1",
                    "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
                }
            ],
            "name": "set_fee_protocol",
            "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read",
                        "write"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "pool_id",
                    "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60"
                },
                {
                    "name": "recipient",
                    "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
                },
                {
                    "name": "zeroForOne",
                    "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
                },
                {
                    "name": "amountSpecified",
                    "concreteTypeId": "1c791a2f63a6d482f33e38564a4c4f67f2351f36419d0c750ce825e233c86ae1"
                },
                {
                    "name": "sqrtPriceLimitX96",
                    "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
                }
            ],
            "name": "swap",
            "output": "3fa8627a84b71ee8f24fd08a49e0c24b26ebd8812d83105363ea2522a6bd1ebf",
            "attributes": [
                {
                    "name": "payable",
                    "arguments": []
                },
                {
                    "name": "storage",
                    "arguments": [
                        "read",
                        "write"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "pool_id",
                    "concreteTypeId": "fe3f72f7108072fbbda0c25d95c9afa4d58421351c8128a8c4840aa4b2f2bb60"
                },
                {
                    "name": "tick",
                    "concreteTypeId": "5505fc50822ba746456a5300ef2739df1284948387efd9f4c4f9bf06827368f2"
                }
            ],
            "name": "tick_info",
            "output": "566fefd02783b1bed85bcd428a63d598af31a37122ce0cf0045531fdc4aeae14",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read"
                    ]
                }
            ]
        },
        {
            "inputs": [
                {
                    "name": "new_owner",
                    "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
                }
            ],
            "name": "transfer_ownership",
            "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
            "attributes": [
                {
                    "name": "storage",
                    "arguments": [
                        "read",
                        "write"
                    ]
                }
            ]
        }
    ],
    "loggedTypes": [
        {
            "logId": "4571204900286667806",
            "concreteTypeId": "3f702ea3351c9c1ece2b84048006c8034a24cbc2bad2e740d0412b4172951d3d"
        },
        {
            "logId": "5557842539076482339",
            "concreteTypeId": "4d216c57b3357523323f59401c7355785b41bdf832f6e1106272186b94797038"
        },
        {
            "logId": "10032608944051208538",
            "concreteTypeId": "8b3afcadf894415a10b09fc3717487e33802c8ffbb030edafe84ca4a71b280bc"
        },
        {
            "logId": "3176768710663004356",
            "concreteTypeId": "2c16264fa4a4e0c4dceefe1b6eee32bbd8f32e19b79110d831a389a95f37c915"
        },
        {
            "logId": "10098701174489624218",
            "concreteTypeId": "8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a"
        },
        {
            "logId": "13928757919242894944",
            "concreteTypeId": "c14ce387a2e1be6031c07283e466ad30db558277d3ff7f694daa635825d612a4"
        },
        {
            "logId": "16343290378128204807",
            "concreteTypeId": "e2cf0802296424074f790dd21c4edfa1afd413199abcb82ac40ddd7d353a16ba"
        },
        {
            "logId": "3903049024573527731",
            "concreteTypeId": "362a6a689aa3d6b3e2d50426f7c94ce2717b22f1df0b7ffe541cbcb25e0b9c65"
        },
        {
            "logId": "9270293908903660410",
            "concreteTypeId": "80a6b331abab8b7ae99401e5abbe1b32a5e31ba95bb98ccc2da6c988a669b828"
        },
        {
            "logId": "1604384485718508140",
            "concreteTypeId": "1643eb307a66426c1cbebe217ae1af8914a092146d96072387f4811c1119c213"
        },
        {
            "logId": "12224862438738316526",
            "concreteTypeId": "a9a76f9e31034cee0ebff18e0c0dc3b3511e277ab8644fb5b42ab97d62b52037"
        },
        {
            "logId": "908674500187138855",
            "concreteTypeId": "0c9c42a4c01c2b27054127b9c4bb9c21c1e449c182cfa19fa56104c4509ac81e"
        },
        {
            "logId": "7845998088195677205",
            "concreteTypeId": "6ce295b0fb4c1c15e8ed1cfa4babda47d8a04940a5266a3229e12243a2e37c2c"
        },
        {
            "logId": "12152039456660331088",
            "concreteTypeId": "a8a4b78066c51a50da6349bd395fe1c67e774d75c1db2c5c22288a432d7a363d"
        },
        {
            "logId": "18149631459970394923",
            "concreteTypeId": "fbe071a6e7ca2b2b5e503e82638f9f11c861a6fb452b65473eca8260db87392d"
        },
        {
            "logId": "12547144180067087194",
            "concreteTypeId": "ae2069277682335a733c89d400032730e629e08e19f5127cba9ddd54854c1ff6"
        },
        {
            "logId": "5056571189421597276",
            "concreteTypeId": "462c8cb4b6f2e25c6687a0e70a48256db33da6c8f214f3a8e2211fd85bb5e773"
        },
        {
            "logId": "7938487056892321597",
            "concreteTypeId": "6e2b2beb181a5f3d2c643986a5df4197407de6383085035d82fe20a2d2d779bf"
        },
        {
            "logId": "2161305517876418151",
            "concreteTypeId": "1dfe7feadc1d9667a4351761230f948744068a090fe91b1bc6763a90ed5d3893"
        },
        {
            "logId": "16280289466020123285",
            "concreteTypeId": "e1ef35033ea9d2956f17c3292dea4a46ce7d61fdf37bbebe03b7b965073f43b5"
        },
        {
            "logId": "12970362301975156672",
            "concreteTypeId": "b3fffbcb3158d7c010c31b194b60fb7857adb4ad61bdcf4b8b42958951d9f308"
        }
    ],
    "messagesTypes": [],
    "configurables": []
};
const storageSlots = [
    {
        "key": "91a2b7e848325f3bd7f4c1b0f42cf543b33a4432db32108fea970020c7c0a8c3",
        "value": "0000000000000000000000000000000000000000000000000000000000000000"
    },
    {
        "key": "91a2b7e848325f3bd7f4c1b0f42cf543b33a4432db32108fea970020c7c0a8c4",
        "value": "0000000000000000000000000000000000000000000000000000000000000000"
    },
    {
        "key": "d79535e42994787b6989bdd5f0f78d7ff9d1721f754c4f996bc6f5d9129c8e69",
        "value": "0000000000000000000000000000000000000000000000000000000000000000"
    },
    {
        "key": "f10b7869766282e9cc437880b3b9e3cab8459f1533e70e07e0cb6b6a8113b7fb",
        "value": "0000000000000000000000000000000000000000000000000000000000000000"
    }
];
class ReactorPoolContractInterface extends fuels_1.Interface {
    constructor() {
        super(abi);
    }
}
exports.ReactorPoolContractInterface = ReactorPoolContractInterface;
class ReactorPoolContract extends fuels_1.Contract {
    static abi = abi;
    static storageSlots = storageSlots;
    constructor(id, accountOrProvider) {
        super(id, abi, accountOrProvider);
    }
}
exports.ReactorPoolContract = ReactorPoolContract;
//# sourceMappingURL=ReactorPoolContract.js.map